### ISSUE TITLE
Violation(s) as an Animation

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#181] opened 2021-08-05 18:05 UTC
Moving this to a new issue for organization's sake:

>Feel free to tell me the following idea is dumb and/or too hard to implement:  Could we show the violation(s) as an animation?
>
>eg.  We highlight the observations that are going to violate protocol in their pre-violation position and then click to show their new spot on the scatter.  Kind of like a "toggle" the problem on and off.  This would be in the initial "take samples" and "play with things" part of the module.  Then you just tell the user this is what is happening with each sample in the simulation.  I think it is powerful to see why the problem is occurring.  This idea could be for the failure to follow protocol and outlier example.  I think it is visually obvious what is going on with the non-random sample.

If I am understanding this correctly, I think it would be doable in theory, but probably pretty complicated.

**Comment by tbyker** [comment] 2021-08-05 18:38
Ok.  I'm headed to another meeting.  Give a little thought to how hard it would be and we can talk about it tomorrow.


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________
From: Ethan Saxenian ***@***.***>
Sent: Thursday, August 5, 2021 2:05 PM
To: ProfessorAmanda/econsimulations ***@***.***>
Cc: Byker, Tanya S. ***@***.***>; Assign ***@***.***>
Subject: [ProfessorAmanda/econsimulations] Violation(s) as an Animation (#181)


Moving this to a new issue for organization's sake:

Feel free to tell me the following idea is dumb and/or too hard to implement: Could we show the violation(s) as an animation?

eg. We highlight the observations that are going to violate protocol in their pre-violation position and then click to show their new spot on the scatter. Kind of like a "toggle" the problem on and off. This would be in the initial "take samples" and "play with things" part of the module. Then you just tell the user this is what is happening with each sample in the simulation. I think it is powerful to see why the problem is occurring. This idea could be for the failure to follow protocol and outlier example. I think it is visually obvious what is going on with the non-random sample.

If I am understanding this correctly, I think it would be doable in theory, but probably pretty complicated.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda%2Feconsimulations%2Fissues%2F181&data=04%7C01%7Ctbyker%40middlebury.edu%7C69c075a315a843778eeb08d9583b9783%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637637835239170974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N2lMYXZ6WkAb0vYRqqiHpHZI7PFTwscJK15mMwllb30%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAP65VZYE3RQPL2GLRAUMJGTT3LHGDANCNFSM5BULIHGA&data=04%7C01%7Ctbyker%40middlebury.edu%7C69c075a315a843778eeb08d9583b9783%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637637835239170974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WXhru1uhjtolhTrzp%2BsbBE0TNCdilUP0C98q5NdNTk4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctbyker%40middlebury.edu%7C69c075a315a843778eeb08d9583b9783%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637637835239180968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OGNEmHV80h26VhbAnvcEFbGWKYpOGlmdmLCYegwL%2Fvw%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Ctbyker%40middlebury.edu%7C69c075a315a843778eeb08d9583b9783%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637637835239180968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ut0fXk96X9r5d9ipHOJtTeoB1scK1%2B5qB5e5Apvf%2BjQ%3D&reserved=0>.

**Comment by ethansaxenian** [comment] 2021-08-09 13:03
Am I correct that we decided against this?

**Comment by ProfessorAmanda** [comment] 2021-08-09 13:33
We decided that we would implement a lower-cost intervention for now: some text explaining what is happening when the samples are taken, with some illustrating arrows. You could either work on this now, or wait until next week when Tanya returns.

**Comment by ethansaxenian** [comment] 2021-08-09 15:44
Not quite sure what you mean by arrows, but I'll certainly need the text before I can work on it!

**Closed** 2021-08-20 19:57 UTC
Labels: OLS Estimators are Consistent
